<?xml version="1.0"?>
<package format="3">
  <name>human_model</name>
  <version>0.0.0</version>
  <description>The human_model package</description>


  <maintainer email="manuel.beschi@unibs.it">Manuel Beschi</maintainer>

  <license>BSD</license>

  <url type="website">https://github.com/JRL-CARI-CNR-UNIBS/human_model</url>

  <author email="manuel.beschi@unibs.it">Manuel Beschi</author>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>eigen</depend>
  <build_depend>pybind11-dev</build_depend>
  <build_depend>python3-dev</build_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <test_depend>gtest</test_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
