[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "human_model"
version = "0.0.1"
description = "A human model package"
authors = [
    { name = "Michele Ferrari", email = "michele.ferrari@unibs.it" }
]

# Tell scikit-build to use Unix Makefiles generator to avoid installing Ninja
[tool.scikit-build.cmake]
args = ["-GUnix Makefiles"]

# [tool.scikit-build] or [tool.setuptools.packages.find] tags are not needed 
# because there’s no Python source package — only the compiled extension.